### ISSUE TITLE
On synched master, one test not passing on test_validate.py

### ISSUE THREAD

**Issue by N-G-Asker** [regro/regolith#947]
I believe something broke with the test validator AFTER the June-26 commit [59240bd993d0e4a3e443574a2a997f7fafbc6378](https://github.com/regro/regolith/commit/59240bd993d0e4a3e443574a2a997f7fafbc6378).

I am now getting one failed automatic test: 

```
FAILED tests/test_validate.py::test_validate - subprocess.CalledProcessError: Command '['regolith', 'validate']' returned non-zero exit status 1.
```

**Comment by N-G-Asker** [comment]
I checked out the June 16 commit and ran the tests `python run_tests.py` with no errors. But the bug seems to also affect [commits](https://github.com/regro/regolith/commit/379f97570624316277531e05118202ad1d923015) made June 28th.

**Comment by N-G-Asker** [comment]
I've tried to pinpoint where the bug nay have been introduced with this in-line [comment](https://github.com/regro/regolith/commit/589ae1978364bb486937568fd7d10fb287ac2697#r77380931), but I am not sure the exact cause.

**Comment by sbillinge** [comment]
Thanks for checking this.   I am getting the same error message.   I can't
quite figure it outso any help is appreciated.   I doubt that change you
point out is the cause.  It just changes which single collection is
validated in testing for debugging. The problem is somewhere in the schema
itself

**Comment by N-G-Asker** [comment]
Please see inline comment [here](https://github.com/regro/regolith/commit/589ae1978364bb486937568fd7d10fb287ac2697#r77393351) for my next hypothesis.

**Comment by sbillinge** [comment]
I think I have a fix for it....I will try and push.

On Thu, Jun 30, 2022 at 8:01 PM Nicholas G. Asker ***@***.***>
wrote:

> Please see inline comment here
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_regro_regolith_commit_589ae1978364bb486937568fd7d10fb287ac2697-23r77393351&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=ZhyLNzmQpdO4xlATjTXxCc5AchRKJyy8-ONuVAIRkLG5w8MzYIaHm4k-AJz8dzdD&s=Q0TxVxSkL51rcYfYXp5wSm9TDKC2DodlOc3OSwbV6Ds&e=>
> for my next hypothesis.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_regro_regolith_issues_947-23issuecomment-2D1171519485&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=ZhyLNzmQpdO4xlATjTXxCc5AchRKJyy8-ONuVAIRkLG5w8MzYIaHm4k-AJz8dzdD&s=NXfSWPp3fL5XaBaRbn2r9DABkhi-gOMjRDOlAvcIXDU&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWUP6WIR6UCKAWD32CDTVRXOGDANCNFSM52JXX2YA&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=ZhyLNzmQpdO4xlATjTXxCc5AchRKJyy8-ONuVAIRkLG5w8MzYIaHm4k-AJz8dzdD&s=edQQkU5142_UAdeZucfACsVr3C-Id-741DgqA8sRRaI&e=>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>


-- 
Simon Billinge
Professor, Columbia University
Physicist, Brookhaven National Laboratory

**Comment by sbillinge** [comment]
this should be fixed by #949 .  @N-G-Asker please can you check and close this issue if it is fixed?

**Comment by N-G-Asker** [comment]
Full test still running (all 400+ checks) but I'm getting more errors than before so far.

**Comment by sbillinge** [comment]
you may not be properly sync'd.  This is what I get on a sync'ed master:
```
========== 462 passed, 35 skipped, 18 warnings in 240.01s (0:04:00) ===========
```
it is skipping some tests that don't run on windows.  But I don't think that is the issue as the CI passed before I merged it.

**Comment by N-G-Asker** [comment]
My master is synched and I am still getting the above errors.

**Comment by sbillinge** [comment]
Interesting.  good luck tracking it down.   Do other people get this?  My
computer skips some tests which don't run on windows but I doubt that it is
that because the CI runs without error if I am not mistaken and this is on
a linux vm...but it could be related to the skipped tests.  I recommend
"slow and steady wins the race" approach.  Take a step back and propose
some hypotheses for what may be happening and then a plan to track this
down.  If others don't get it, the most likely is something with your local
environment.  Be aware that conda makes a virtual environment in principle,
but things in your base environment are inherited by the vm and this can
often cause headaches and problems.  It is recommended that you keep your
base empty if you can....  It tends not to happen because we type "conda
install" then realize that we forgot to activate the env....

S

On Sun, Jul 3, 2022 at 11:37 PM Nicholas G. Asker ***@***.***>
wrote:

> My master is synched and I am still getting the above errors.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_regro_regolith_issues_947-23issuecomment-2D1173176198&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=A_jG42KNEwJP58uhxTHUkL7ypdWle1ovfxtDYZ0-ZmMWQXS5Q4HT_8-_Mnb4kMGU&s=F1fmii4aWv07NRwXMbe1SZIKOs4NKMe8tpNXwkTWqaQ&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABAOWUP5W2XC5EYGQEYYVZDVSIB2DANCNFSM52JXX2YA&d=DwMCaQ&c=009klHSCxuh5AI1vNQzSO0KGjl4nbi2Q0M1QLJX9BeE&r=6Pin9WIW2wJZzVMqXib07fokbkHzCKPr15sA4fQTrA8&m=A_jG42KNEwJP58uhxTHUkL7ypdWle1ovfxtDYZ0-ZmMWQXS5Q4HT_8-_Mnb4kMGU&s=fuj20znDzu1CA-5sGzXgwMQ5ikBf4YWDux4v6vP9btg&e=>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>


-- 
Simon Billinge
Professor, Columbia University
Physicist, Brookhaven National Laboratory

**Comment by sbillinge** [comment]
wait, I think I may have tracked it down....I have unmerged edits locally.  Give me  a sec....  Sorry about that!

**Comment by sbillinge** [comment]
no, that wasn't it. I removed those unmerged edits and the tests still passed.....

**Comment by N-G-Asker** [comment]
Sounds like a good plan of attack.

As the first step, I have notes out to a couple summers to see if they can replicate the issue I'm having -- thanks for the guidance
